services:
  frontend:
    image: node:14  # Verwende das richtige Image
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app  # Binde das lokale Frontend-Verzeichnis
    ports:
      - "3000:3000"  # Mappe Port 3000 auf den Host
    command: npm start
    networks:
      - app-network

  backend:
    image: node:14
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app  # Binde das lokale Backend-Verzeichnis
    ports:
      - "3001:3001"
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
