services:
  backend:
    build: # statt image:
      context: ./backend # Pfad zu deinem Code
      dockerfile: Dockerfile.dev # Für Devlopment, damit Änderungen sofort vom Container übernommen werden ohne neustart
    container_name: backend
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # fallback für macOS/Windows
      - MONGO_URI=mongodb+srv://noellinder:w5WiwxRaVhD0TL4k@coffeefirst.vbrlytg.mongodb.net/coffeefirst?authMechanism=SCRAM-SHA-1
    volumes:
      - ./backend:/app # Live-Code
      - /app/node_modules # keeps container’s node_modules
    ports:
      - '3001:3001'
 
  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
