services:
  backend:
    image: node:18
    container_name: backend
    working_dir: /app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/admin
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run server"
    ports:
      - '3001:3001'
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  mongodb_data: